[project]
name = "email-chunker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pgvector>=0.4.1",
    "pypdf2>=3.0.1",
    "python-magic>=0.4.27",
    "transformers>=4.55.4",
]
